# Generated by Django 4.1.4 on 2022-12-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionHeuresAbsences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_A', models.DateField(blank=True, null=True)),
                ('nombre_heures_A', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_E', models.CharField(max_length=50)),
                ('nom_E', models.CharField(max_length=50)),
                ('prenoms_E', models.CharField(max_length=75)),
                ('sexe_E', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10)),
                ('classe', models.CharField(choices=[('AS1', 'AS1'), ('AS2', 'AS2'), ('AS3', 'AS3'), ('ISE_eco', 'ISE_eco'), ('ISE_math', 'ISE_math'), ('ISE2A', 'ISE2A'), ('ISE2B', 'ISE2B'), ('ISE3', 'ISE3')], max_length=50)),
            ],
            options={
                'verbose_name': 'Eleve',
                'verbose_name_plural': 'Eleves',
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_J', models.DateField(blank=True, null=True)),
                ('duree_J', models.IntegerField(blank=True, null=True)),
                ('Motifs', models.CharField(choices=[('CAS DE MALADIE', 'CAS DE MALADIE'), ('AUTORISATION ABSENCE', 'AUTORISATION ABSENCE'), ('AUTRES A PRECISER', 'AUTRES A PRECISER')], max_length=50)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHeuresAbsences.eleve', verbose_name='Eleve')),
            ],
            options={
                'verbose_name': 'Justification',
                'verbose_name_plural': 'Justifications',
            },
        ),
        migrations.RemoveField(
            model_name='absences',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='absences',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='eleves',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='motifs',
            name='absence',
        ),
        migrations.RemoveField(
            model_name='motifs',
            name='eleve',
        ),
        migrations.DeleteModel(
            name='Semestres',
        ),
        migrations.DeleteModel(
            name='Absences',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Eleves',
        ),
        migrations.DeleteModel(
            name='Motifs',
        ),
        migrations.AddField(
            model_name='absence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHeuresAbsences.eleve', verbose_name='Eleve'),
        ),
    ]
